language: node_js
node_js:
  - 0.10
  - 6
  - 8
  - 10
  - 12
after_success:
  - if [ `node -p 'process.version.slice(0, 3)'` != "v8." ]; then exit; fi
  - npm install -g nyc
  - npm install -g codecov
  - nyc --reporter lcov npm test && codecov
